from flask_restful import reqparse

parser = reqparse.RequestParser()
parser.add_argument('surname', required=True)
parser.add_argument('name', required=True)
parser.add_argument('age', required=True, type=int)
parser.add_argument('position')
parser.add_argument('speciality')
parser.add_argument('address')
parser.add_argument('email')
parser.add_argument('password')

job_parser = reqparse.RequestParser()
job_parser.add_argument('team_leader', required=True)
job_parser.add_argument('description', required=True)
job_parser.add_argument('work_size', type=int)
job_parser.add_argument('collaborators')
job_parser.add_argument('start_date')
job_parser.add_argument('end_date')
job_parser.add_argument('is_finished')